plugins {
    // see https://fabricmc.net/develop/ for new versions
    id 'fabric-loom' version '1.8-SNAPSHOT' apply false
    // see https://projects.neoforged.net/neoforged/moddevgradle for new versions
    id 'net.neoforged.moddev' version '2.0.49-beta' apply false

    id 'architectury-plugin'  version '3.4-SNAPSHOT'
}

repositories {
    maven { url = "https://maven.createmod.net" } // Create, Ponder, Flywheel
    maven { url = "https://mvn.devos.one/snapshots" } // Registrate
    maven { url = "https://raw.githubusercontent.com/Fuzss/modresources/main/maven/" } // ForgeConfigAPIPort
}

//subprojects {
//    apply(plugin = "architectury-plugin")
//}